version: '3.4'

networks:
  frontend:
  backend:

services:
  catalog:
    image: yoga/catalogapi
    build:
      context: .\CatalogAPI
      dockerfile: Dockerfile
    environment:
      ExternalCatalogBaseUrl: http://localhost:6610
      DatabaseServer: mssqlserver
      DatabaseName: YogaCatalogDb
      DatabaseUser: sa
      DatabasePassword: CatalogApi(!)
    ports:
      - "6610:80"
    container_name: yogacatalogapi
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlserver
  
      
  webmvc:
    image: yoga/webmvc
    build:
      context: .\WebApp
      dockerfile: Dockerfile
    environment:
      CatalogUrl: http://catalog
    ports:
      - "6611:80"
    networks:
      - frontend
    depends_on:
      - catalog


  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: CatalogApi(!)
    ports:
      - "1400:1433"
    container_name: yogasqlserver
    networks:
      - backend





